# -*- yaml -*-
version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3

jobs:
  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - store_artifacts:
          path: .version
      - sixrs-gke/docker-login
      - run:
          name: Publish Docker Image
          command: |
            VERSION=$(cat .version)
            GCR_NAME="gcr.io/${GCLOUD_PROJECT}/firmware-builder:${VERSION}"
            docker build -t ${GCR_NAME} .
            docker push ${GCR_NAME}

workflows:
  version: 2
  build-deploy:
    jobs:
      - publish:
          context: 6rs-circle